### Exercise 1: List Filtering

In [1]:
#1)  Given a list of numbers, create a new list that contains only the even numbers.

In [2]:
a=[1,2,4,5,12,11]
b=[]

In [3]:
for num in a:
    if num%2==0:
        b.append(num)
print(b)
        

[2, 4, 12]


### Exercise 2: Tuple Unpacking

In [5]:
#2: Create a tuple of coordinates (x, y, z), and then unpack and print each coordinate separately.

In [6]:
a=(5,6,7)
(x,y,z)=a
print("x coordinate is",x)
print("y coordinate is",y)
print("z coordinate is",z)


x coordinate is 5
y coordinate is 6
z coordinate is 7


### Exercise 3: List Concatenation

In [7]:
#3: Given two lists, merge them into a single list without duplicates.

In [8]:
a=[1,11,12,2]
b=[2,5,7]
c=a+b
print(list(set(c)))

[1, 2, 5, 7, 11, 12]


### Exercise 4: Conditional List Comprehension

In [9]:
# 4 Create a list that contains squares of even numbers and cubes of odd numbers from 1 to 10 using list comprehension.

In [10]:
a=[1,2,3,4,5,6,7,8,9,10]
b=[i**2 if i%2==0 else i**3 for i in a]
print(b)


[1, 4, 27, 16, 125, 36, 343, 64, 729, 100]


## Exercise 5: List of Lists

In [12]:
#Problem: Given a list of lists, flatten it into a single list.
    
nested_list = [[1, 2, 3], [4, 5], [6, 7, 8]]   

In [13]:
a=[]
for i in nested_list:
    for j in i:
        a.append(j)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8]


## Exercise 6: List of Tuples

In [14]:

#Problem: Given a list of tuples, sort them based on the second element of each tuple.
data = [(1, 5), (3, 2), (2, 8), (4, 1)]   

In [15]:
sort_list=sorted(data,key=lambda i: i[1])        
print(sort_list)       
    

[(4, 1), (3, 2), (1, 5), (2, 8)]


## Exercise 7: Nested List Comprehension

Problem: Create a matrix represented as a list of lists and transpose it using nested list comprehensions.


In [16]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
import numpy as np
a=np.transpose(matrix)
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Exercise 8: Fibonacci Sequence

Problem: Generate the first 10 numbers of the Fibonacci sequence using a list.
Each number should be the sum of the previous two.

In [18]:
x = [0, 1]
for i in range(2, 10):
    y = x[i - 1] + x[i - 2]
    x.append(y)
print(x)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## Exercise 9: Prime Numbers

Problem: Generate a list of prime numbers from 1 to 50

In [22]:
def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

primes = [x for x in range(1, 51) if is_prime(x)]
print(primes)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]
